name: Generate GitHub Contribution Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Nithin-kumar-hub
          outputs: |
            dist/github-snake.svg?color_snake=#39ff88&color_dots=#161b22,#0d3b2e,#176b52,#20a86b,#39ff88
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#39ff88&color_dots=#161b22,#0d3b2e,#176b52,#20a86b,#39ff88
            dist/github-snake-light.svg?palette=github-light&color_snake=#087f5b&color_dots=#ebedf0,#c6f6df,#8ce9c1,#45c99a,#087f5b

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
          commit_message: "Update contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
